# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Dashboard' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Dashboard
  pod 'OAuthSwift'
  pod 'Alamofire'
  pod 'Nuke'

  target 'DashboardTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DashboardUITests' do
    # Pods for testing
  end

end
